### PR TITLE
Reorganization per #7

### PR DESCRIPTION
**Pull request by arnavs**
Has the Jupyter-based notebooks (which we had essentially already done, with the `quantecon/base` and `quantecon/extended`), as well as the no-jupyter versions.

We need to figure out how the `R` notebook fits into this scheme. 

We can hold off on merging until the Jupinx permutations are done. But figured we can start discussing/reviewing now.

### CODE REVIEW

**Comment by arnavs** [comment]
cc @jlperla @sglyon @mmcky

**Comment by sglyon** [comment]
Thanks @arnavs 

I'd really love to figure out how to not repeat the bulk of the Dockerfile each time. 

Can you remind me what was difficult about "inheriting" `FROM` a base image?

**Comment by arnavs** [comment]
Also, the custom `ipopt` code was removed in favor of whatever that package does internally, which I think makes sense for robustness and maintainability. The only reason to revisit this is: 

> If you prefer to compile your own version of Ipopt in order to use commercial sparse linear algebra libraries, use the instructions below.

**Comment by arnavs** [comment]
Merging this just so that we can press ahead with the Docker-based infrastructure for the lectures, etc. 

Still ironing out some kinks with Cairo on the `all-notebook`, and ofc always open to simplifications etc.

**Pull request merged**
